neo4j:
  uri: bolt://127.0.0.1:7687     # or bolt+s://<host>:7687
  user: tobias@truenorthmaterials.com
  password_env: Hackathon    # read from env for safety
  database: neo4j                 # optional
models:
  chat: gpt-4o
  temperature: 0.3

  vector:
  chroma_dir: ./agent/GraphTool/chroma_db_mof_summaries
